@startuml
set separator none
title Url Shortener - Containers

top to bottom direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<UrlShortener.API>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
  roundCorner 20
  shadowing false
}
skinparam database<<UrlShortener.AnalyticsDB>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
  shadowing false
}
skinparam rectangle<<UrlShortener.AnalyticsServer>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UrlShortener.BackEnd>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
  roundCorner 20
  shadowing false
}
skinparam database<<UrlShortener.DataBase>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
  shadowing false
}
skinparam rectangle<<UrlShortener.EventBus>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
  roundCorner 20
  shadowing false
}
skinparam rectangle<<TgBot>> {
  BackgroundColor #5e5e5d
  FontColor #ffffff
  BorderColor #414141
  roundCorner 20
  shadowing false
}
skinparam rectangle<<cUrl>> {
  BackgroundColor #5e5e5d
  FontColor #ffffff
  BorderColor #414141
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UrlShortener.cache>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
  roundCorner 20
  shadowing false
}
skinparam rectangle<<UrlShortener>> {
  BorderColor #6d6d04
  FontColor #6d6d04
  shadowing false
}

rectangle "==cUrl\n<size:10>[Software System]</size>" <<cUrl>> as cUrl
rectangle "==Tg Bot\n<size:10>[Software System]</size>" <<TgBot>> as TgBot

rectangle "Url Shortener\n<size:10>[Software System]</size>" <<UrlShortener>> {
  rectangle "==cache\n<size:10>[Container]</size>" <<UrlShortener.cache>> as UrlShortener.cache
  database "==DataBase\n<size:10>[Container]</size>" <<UrlShortener.DataBase>> as UrlShortener.DataBase
  rectangle "==API\n<size:10>[Container]</size>" <<UrlShortener.API>> as UrlShortener.API
  rectangle "==EventBus\n<size:10>[Container]</size>" <<UrlShortener.EventBus>> as UrlShortener.EventBus
  rectangle "==AnalyticsServer\n<size:10>[Container]</size>" <<UrlShortener.AnalyticsServer>> as UrlShortener.AnalyticsServer
  database "==AnalyticsDB\n<size:10>[Container]</size>" <<UrlShortener.AnalyticsDB>> as UrlShortener.AnalyticsDB
  rectangle "==BackEnd\n<size:10>[Container]</size>" <<UrlShortener.BackEnd>> as UrlShortener.BackEnd
}

cUrl .[#707070,thickness=2].> UrlShortener.API : "<color:#707070>sending request"
TgBot .[#707070,thickness=2].> UrlShortener.API : "<color:#707070>sending request"
UrlShortener.API .[#707070,thickness=2].> UrlShortener.EventBus : "<color:#707070>sending data"
UrlShortener.EventBus .[#707070,thickness=2].> UrlShortener.AnalyticsServer : "<color:#707070>sending data"
UrlShortener.EventBus .[#707070,thickness=2].> UrlShortener.AnalyticsDB : "<color:#707070>retrieving or writing data"
UrlShortener.EventBus .[#707070,thickness=2].> UrlShortener.BackEnd : "<color:#707070>sending data"
UrlShortener.BackEnd .[#707070,thickness=2].> UrlShortener.DataBase : "<color:#707070>retrieving or writing data"
UrlShortener.BackEnd .[#707070,thickness=2].> UrlShortener.cache : "<color:#707070>checking the cache for the necessary data"
@enduml