@startuml
set separator none

skinparam {
  shadowing false
  arrowFontSize 15
  defaultTextAlignment center
  wrapWidth 100
  maxMessageSize 100
}
hide stereotype

skinparam rectangle<<_transparent>> {
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

skinparam rectangle<<1>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
  roundCorner 20
}
rectangle "==Container" <<1>>

skinparam database<<2>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
}
database "==Container, AnalyticsDataBase" <<2>>

skinparam database<<3>> {
  BackgroundColor #b8b804
  FontColor #ffffff
  BorderColor #808002
}
database "==Container, DataBase" <<3>>

skinparam rectangle<<4>> {
  BackgroundColor #5e5e5d
  FontColor #ffffff
  BorderColor #414141
  roundCorner 20
}
rectangle "==Software System, S1" <<4>>

rectangle "." <<_transparent>> as 5
5 .[#707070,thickness=2].> 5 : "<color:#707070>Relationship"


@enduml